spring.application.name=resume-parsing
spring.datasource.url= jdbc:mysql://localhost:3306/parsing
spring.datasource.username= root
spring.datasource.password= Root1234
spring.jpa.hibernate.ddl-auto =update
spring.jpa.show-sql =true